#!/bin/bash

echo "Congrats on your new Mac! Let's get you setup, Ryan"

if ! command -v brew &> /dev/null
then
  echo "***********************"
  echo "*   Installing Brew   *"
  echo "***********************"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "**************************"
echo "*   Installing Formula   *"
echo "**************************"

brew install \
  awscli \
  azure-cli \
  caddy \
  cmake \
  git \
  git-extras \
  git-secrets \
  imagemagick \
  jq \
  nvm \
  python \
  reattach-to-user-namespace \
  shellcheck \
  terraform \
  the_silver_searcher \
  tmux \
  vim \
  watch \
  zsh

echo "*****************************"
echo "*   Installing Sparkbox bins "
echo "*****************************"
brew tap sparkbox/brew
brew install sb


echo "***************************"
echo "*   Installing Heroku CLI *"
echo "**************************"
brew tap heroku/brew && brew install heroku

echo "************************"
echo "*   Installing Casks   *"
echo "************************"
brew install --cask \
  1password \
  alfred \
  bartender \
  docker \
  harvest \
  iterm2 \
  microsoft-teams \
  nvalt \
  obs \
  recordit \
  sequel-pro \
  xbar \
  zoom

echo "***********************"
echo "*   Setup oh-my-zsh   *"
echo "***********************"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/cromwellryan/git-poooosh.git "$HOME/.oh-my-zsh/custom/plugins/git-poooosh"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

echo "************************"
echo "*   Setup Dotfiles     *"
echo "************************"
if [ ! -d ~/dotfiles ]; then
  git clone https://github.com/cromwellryan/dotfiles.git ~/dotfiles
fi

cd ~/dotfiles

ln -s "$PWD/cromwell.zsh-theme" "$HOME/.oh-my-zsh/themes/cromwell.zsh-theme"

mkdir -p "~/Library/Application Support/xbar/"
ln -sf "$PWD/dotfiles" "~/Library/Application Support/xbar/plugins"

for link in .agignore .bash_gpg .bash_profile .bashrc .gitconfig .gitignore .gitmessage.txt .profile .tern-project .tmux.conf .vimrc .zshenv .zshrc tmuxinator.zsh .vim; do
  if [ -L "$HOME/$link" ]; then
    echo "Link '$link' exists"
  else
    ln -s "$PWD/$link" "$HOME/$link"
  fi
done

echo "*****************"
echo "*   Setup NVM   *"
echo "*****************"
NODE_VERSION=14 PROFILE=/dev/null sh -c "$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

echo "****************"
echo "*   Setup Vim  *"
echo "****************"
if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim -c "BundleInstall" -c ":qa"

cd ~/.vim/bundle/YouCompleteMe
python3 install.py --js-completer --ts-completer --system-boost

brew tap homebrew/cask-fonts
brew install --cask font-fira-code
