#!/bin/bash

echo "Congrats on your new Mac! Let's get you setup, Ryan"

echo "***********************"
echo "*   Installing Brew   *"
echo "***********************"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "**************************"
echo "*   Installing Formula   *"
echo "**************************"

brew install \
  awscli \
  azure-cli \
  caddy \
  git \
  git-extras \
  git-secrets \
  imagemagick \
  iterm2 \
  jq \
  nvm \
  reattach-to-user-namespace \
  shellcheck \
  terraform \
  the_silver_searcher \
  tmux \
  vim \
  zsh

echo "***************************"
echo "*   Installing Heroku CLI *"
echo "**************************"
brew tap heroku/brew && brew install heroku

echo "************************"
echo "*   Installing Casks   *"
echo "************************"
brew install --cask \
  1password \
  iterm2 \
  microsoft-teams \
  nvalt \
  obs \
  recordit \
  sequel-pro \
  zoom \
  docker

git clone git@github.com:cromwellryan/dotfiles.git ~/dotfiles

or link in .agignore .bash_gpg .bash_profile .bashrc .gitconfig .gitignore .gitmessage.txt .profile .tmux.conf .vimrc .zshenv .zshrc tmuxinator.zsh; do
  if [ -L "$HOME/$link" ]; then
    echo "Link '$link' exists"
  else
    ln -s "$PWD/$link" $HOME
  fi
done
